version: "3.8"

services:

  doraapp:
    build: .
    container_name: doraapp
    restart: unless-stopped
    expose:
      - 8086
    volumes:
      - /var/log:/var/log
    links:
      - ddb
    env_file:
      - server.env
    networks:
      - doraproject

  ddb:
    image: postgres:12.3-alpine
    container_name: doradb
    restart: unless-stopped
    volumes:
      - ./ddb_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5434:5432"
    networks:
      - doraproject

networks:
  doraproject:
